services:
  - type: web
    name: voicebot-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health/live
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: REDIS_URL
        fromDatabase:
          name: voicebot-redis
          property: connectionString
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        value: us-east-1-aws
      - key: PINECONE_INDEX_NAME
        value: voicebot-index
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-1.5-flash
      - key: JINA_API_KEY
        sync: false
      - key: JINA_MODEL
        value: jina-embeddings-v2-base-en

databases:
  - name: voicebot-redis
    plan: starter
